### ISSUE TITLE
Add README.md 

### ISSUE THREAD

**Issue by n-ce** [n-ce/Touch-the-ball#1]

**Comment by LiamNgn** [comment]
Hello. I came cross your issue and I was wondering if I can do this? Thank you.

**Comment by themonikanayak** [comment]
Hello. I came across your issue and gave it a try. Please review my pull request. Thank You.

**Comment by n-ce** [comment]
> Hello. I came across your issue and gave it a try. Please review my pull request. Thank You.

That's a cool description! Great work.

**Comment by n-ce** [comment]
> Hello. I came cross your issue and I was wondering if I can do this? Thank you.

I have merged the most recent pull request. You might want to take a look and provide changes.

**Comment by themonikanayak** [comment]
> Thanks for your appreciation. I will try to make it better in the future.



> > Hello. I came cross your issue and I was wondering if I can do this? Thank you.
> 
> I have merged the most recent pull request. You might want to take a look and provide changes.

Thanks for your appreciation. I will try to make it better in the future.

**Comment by themonikanayak** [comment]
> > Hello. I came cross your issue and I was wondering if I can do this? Thank you.
> 
> I have merged the most recent pull request. You might want to take a look and provide changes.

Thanks for your appreciation. I will try to make it better in the future.
